version: "3"
services:
  avbot:
    build: .
    env_file:
      - .env
    depends_on:
      - redis
      - db
  redis:
    image: "redis:alpine"
  db:
    image: postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
