version: 2.1
executors:
  docker-publisher:
    environment:
      IMAGE_NAME: b00bl1k/avbot
    docker:
      - image: docker:stable
jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            docker build -t $IMAGE_NAME:$CIRCLE_SHA1 .
  build-master:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: |
            docker build -t $IMAGE_NAME:$CIRCLE_SHA1 .
      - run:
          name: Archive docker image
          command: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
          root: .
          paths:
             - ./image.tar
  publish:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Load archived docker image
          command: docker load -i /tmp/workspace/image.tar
      - run:
          name: Publish docker image
          command: |
            echo "$DOCKERHUB_PASS" | docker login --username "$DOCKERHUB_USERNAME" --password-stdin
            docker push $IMAGE_NAME:$CIRCLE_SHA1
            docker tag $IMAGE_NAME:$CIRCLE_SHA1 $IMAGE_NAME:latest
            docker push $IMAGE_NAME:latest
workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - build-master:
          filters:
            branches:
              only: master
      - publish:
          requires:
            - build-master
          context: global
